apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy666
  labels:
    app: autodeploy666
  namespace: namespace-workflow-1699953586059
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy666
  template:
    metadata:
      labels:
        app: autodeploy666
    spec:
      containers:
        - name: autodeploy666
          image: acrworkflow1699953586059.azurecr.io/image-workflow-1699953586059:latest
          ports:
            - containerPort: 5000